name: CMake

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: List tooling
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC" /A:D /B

      - name: List 14.38
        shell: cmd
        run: dir "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.38.33130" /A:D /B

      - name: Configure CMake on Windows
        shell: cmd
        if: runner.os == 'Windows'
        run: |
          cmake -B ${{github.workspace}}/build --trace-expand -G "Visual Studio 17 2022" -T v143,version=14.38 -DCMAKE_BUILD_TYPE=Debug -DENABLE_TEST=1

      - name: Build on Windows
        shell: cmd
        working-directory: ${{github.workspace}}/build
        if: runner.os == 'Windows'
        run: cmake --build . --config Debug
