name: CMake

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}

    steps:
      - name: Test
        run: |
          curl -f -L --retry 5 https://wasmtime.dev/install.sh | bash -s -- --version dev
          VERSION_OUTPUT="$(~/.wasmtime/bin/wasmtime --version)"
          echo $VERSION_OUTPUT
          WASMTIME_VERSION=$(echo $VERSION_OUTPUT | cut -d' ' -f2)
          curl -f -L --retry 5  -o ~/.wasmtime/bin/wasi_snapshot_preview1.command.wasm https://github.com/bytecodealliance/wasmtime/releases/download/${WASMTIME_VERSION}/wasi_snapshot_preview1.command.wasm
          ls ~/.wasmtime/bin
