name: CMake

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: ls /home/runner/work/GitHubActionLearn/GitHubActionLearn
      - name: Install Linux deps
        run: | 
          docker build . -t mynginx:1.0
          docker build . -t mynginx:1.0
      
